//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class block
    {
        public int SympId { get; set; }
        public string effectorName { get; set; }
        public string place { get; set; }
        public string type_effector { get; set; }
        public int EffectorId { get; set; }
        public int blockId { get; set; }
    }
}
