//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoboDbMainEntities : DbContext
    {
        public RoboDbMainEntities()
            : base("name=RoboDbMainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<block> blocks { get; set; }
        public virtual DbSet<EffectorsDb> EffectorsDbs { get; set; }
        public virtual DbSet<ODB> ODBs { get; set; }
        public virtual DbSet<Qdb> Qdbs { get; set; }
    }
}
